apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: wordpress
spec:
  name: wordpress
  deploymentstrategy: docker
  image:
    repository: bitnami/wordpress
    tag: latest
    containerPort: "8080"
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: mysql2
        spec:
          mysql:
            auth:
              createDatabase: true
              database: wordpress
              password: wordpress
              rootPassword: wordpress
              username: wordpress
            global:
              storageClass: standard
            primary:
              persistence:
                accessModes:
                - ReadWriteMany
                size: 1Gi
  envVars:
  - name: WORDPRESS_DATABASE_HOST
    value: mysql2
  - name: WORDPRESS_DATABASE_USER
    value: wordpress
  - name: WORDPRESS_DATABASE_PASSWORD
    value: wordpress
  - name: WORDPRESS_DATABASE_NAME
    value: wordpress
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /bitnami/wordpress
    name: wordpress-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
